# Pages Configuration
name = "programme-candito"
pages_build_output_dir = "app/dist"

[[kv_namespaces]]
binding = "CANDITO_SUBS"
id = "15eeb67e39fa4b55b1e7105ebda9f11f" # Injecté par Antigravity

[vars]
VAPID_PUBLIC_KEY = "BDudDlJbtu4YN-BHT9pkn0cCRUVSD_3BeocMK3mCDcYsE2frcq1C_zh5oG_sNc6ylt7rv7xVwdi-T2iu-Zm69dE"
