# Worker Configuration
name = "candito-scheduler"
main = "training-reminder.ts"
compatibility_date = "2026-04-14"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CANDITO_SUBS"
id = "15eeb67e39fa4b55b1e7105ebda9f11f" # Injecté par Antigravity

[vars]
VAPID_PUBLIC_KEY = "BDudDlJbtu4YN-BHT9pkn0cCRUVSD_3BeocMK3mCDcYsE2frcq1C_zh5oG_sNc6ylt7rv7xVwdi-T2iu-Zm69dE"

[triggers]
crons = ["0 8 * * *"]
